version: '3.8'
services:
  discovery:
    build: ./discovery
    ports:
      - "8761:8761"
    networks:
      - net

  gemini-ai-agent:
    build: ./gemini-ai-agent
    depends_on:
      - discovery
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - net

  telegram-bot:
    build: ./telegram-bot
    depends_on:
      - discovery
      - gemini-ai-agent
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    networks:
      - net

networks:
  net:
