version: '3.8'
services:
  discovery:
    build: ./discovery
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 160m

  gemini-ai-agent:
    build: ./gemini-ai-agent
    depends_on:
      - discovery
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 160m

  telegram-bot:
    build: ./telegram-bot
    depends_on:
      - discovery
      - gemini-ai-agent
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 160m

networks:
  net:
