FROM maven:3.9.9-eclipse-temurin-17 AS build

WORKDIR /build
COPY ../ /build
RUN mvn -pl gemini-ai-agent -am clean package -DskipTests

FROM eclipse-temurin:17
WORKDIR /app
COPY --from=build /build/gemini-ai-agent/target/gemini-ai-agent-*.jar app.jar

ENTRYPOINT ["java", "-Xms64m", "-Xmx128m", "-jar", "/app/app.jar"]